# Generated by Django 4.1.7 on 2023-02-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date_construct', models.DateField()),
                ('description', models.TextField()),
                ('size', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to=None)),
                ('rank', models.IntegerField()),
                ('cost', models.CharField(max_length=100)),
            ],
        ),
    ]
